project:
  root: '{process.cwd}'

cocos:
  editor: '/Applications/CocosCreator/Creator/3.7.3/CocosCreator.app/Contents/MacOS/CocosCreator'
  iosBuildConfig: '{project.root}/build-config/buildConfig_ios.json'
  iosBuildCommand: "{cocos.editor} --project {project.root} --build 'configPath={cocos.iosBuildConfig}'"
  # 暂时不可用
  androidBuildConfig: ''
  androidBuildCommand: ''

fastlane:
  root: '{project.root}/build/ios/proj'
  settingRoot: '{project.root}/pack_configs'

manifest:
  version:
    root: '{project.root}/assets'

deploy:
  - local:
      buildCommand: 'pnpm test:commad'
      distDir: './remote-assets'
      distZip: './remote-assets.zip'
    server:
      name: '' # game1
      host: '' # 216.224.000.000
      port: '' # 22
      username: '' # root
      password: '' # 123
      distDir: '/root/game/frontend'
      distZipName: '' # game
      backup: false
      command:
        beforePutFile:
          command: ''
        afterPutFile:
          command: ''
        beforeBackup:
          command: ''
        afterBackup:
          command: ''
        beforeRmOldFile:
          command: ''
        afterRmOldFile:
          command: ''
        beforeUnzip:
          command: ''
        afterUnzip:
          command: ''
        success:
          command: ''

tasks:
  fastlaneForceMatch:
    root: '{fastlane.root}/fastlane'
    command: 'fastlane force_match'
  fastlaneBuildIPA:
    root: '{fastlane.root}/fastlane'
    command: 'fastlane beta'
  installFastlaneDep:
    root: '{fastlane.root}'
    command: 'bundle install'
  prepareFastlaneDirectory:
    type: 'prepareFastlaneDirectory'
  updateManifestVersion:
    type: 'updateManifestVersion'
  assetsCompressAndDeploy:
    type: 'assetsCompressAndDeploy'
  cocosBuild:
    type: 'cocosBuild'

pipelines:
  cocosBuild: ['cocosBuild']
  ipa: ['prepareFastlaneDirectory', 'installFastlaneDep', 'fastlaneBuildIPA']
  version: ['updateManifestVersion']
  base:
    [
      'updateManifestVersion',
      'cocosBuild',
      'cocosBuild',
      'prepareFastlaneDirectory',
      'installFastlaneDep',
      'fastlaneBuildIPA',
    ]
  hotUpdate: ['cocosBuild']
  forceMatch: ['fastlaneForceMatch']
  deploy: ['assetsCompressAndDeploy']
